<a href="https://colab.research.google.com/github/fatemeh-ict/NLp/blob/main/self_attention_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [2]:
L,d_v,d_k=4,8,8
q=np.random.randn(L,d_k)
k=np.random.randn(L,d_k)
v=np.random.randn(L,d_v)



In [3]:
print('Q:' ,q)
print('K:' ,k)
print('V:' ,v)


Q: [[-9.77924898e-01  4.44572771e-01 -1.76604134e+00  1.01049752e+00
   6.64773710e-01  9.34487037e-01  6.02586918e-01 -1.33283925e+00]
 [-3.45223993e-01  1.30391441e-03 -2.95794871e-01  8.43922012e-01
  -4.60591697e-01  1.00572154e+00 -1.81640797e+00 -1.88911176e+00]
 [ 1.32401673e+00  5.71255374e-01 -1.36280135e+00  3.23912908e-01
   1.03632534e+00  4.23072523e-02 -4.59872772e-02  1.28447456e-02]
 [-4.74509385e-01  1.23100644e-01 -8.53185485e-01  1.50185937e+00
  -3.71231181e-01  2.96330877e-01  3.29859415e-02  4.24694493e-01]]
K: [[ 0.21622947  0.58724895  0.23548883 -1.46703762 -1.62682373 -1.40717059
  -1.39956953  0.16377519]
 [ 0.37623156 -0.7179211  -2.73028538  0.59713483  0.82860094  0.36641916
  -0.95163053 -0.26991242]
 [ 0.04004255 -1.05290654 -0.95500036 -0.96876043  0.49361471  0.80644317
   0.60348088  1.26782241]
 [ 0.63217599  1.40273558  0.65586497  0.53894631 -1.7029201   0.54899075
   1.94928337 -0.37493385]]
V: [[-0.23143078  0.41771085 -0.9566029   2.51162707  0.

In [4]:
#self attention
np.matmul(q,k.T)

array([[-5.30680279,  5.41766156, -0.04401311,  0.4470241 ],
       [ 0.18527573,  3.4060323 , -3.45779387, -1.45150534],
       [-1.85334248,  4.91677515,  0.97341649, -0.9169213 ],
       [-2.22418414,  2.6143085 , -0.1746911 ,  0.82247787]])

In [5]:
#wy we need sqrt(d_k) in deminator
q.var(),k.var(),np.matmul(q,k.T).var()

(0.8278144454356797, 1.0997322452591938, 7.787314816294325)

In [6]:
scale=np.matmul(q,k.T)/math.sqrt(d_k)

In [7]:
q.var(),k.var(),scale.var()

(0.8278144454356797, 1.0997322452591938, 0.9734143520367903)

In [8]:
scale

array([[-1.87623812,  1.91543261, -0.01556098,  0.15804689],
       [ 0.06550486,  1.20421427, -1.22251475, -0.51318463],
       [-0.65525552,  1.73834252,  0.3441547 , -0.32418064],
       [-0.78636784,  0.92429763, -0.06176263,  0.29078984]])

In [10]:
mask=np.tril(np.ones( (L,L) ))

In [11]:
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [12]:
mask[mask==0]=-np.infty
mask[mask==1]=0

In [13]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [14]:
scale+mask

array([[-1.87623812,        -inf,        -inf,        -inf],
       [ 0.06550486,  1.20421427,        -inf,        -inf],
       [-0.65525552,  1.73834252,  0.3441547 ,        -inf],
       [-0.78636784,  0.92429763, -0.06176263,  0.29078984]])

In [15]:
#softmax
def softmax(x):
  return (np.exp(x).T/np.sum(np.exp(x),axis=1)).T

In [16]:
attention=softmax(scale+mask)

In [17]:
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.24255739, 0.75744261, 0.        , 0.        ],
       [0.0681686 , 0.7466392 , 0.18519221, 0.        ],
       [0.08670861, 0.47972771, 0.1789593 , 0.25460438]])

In [18]:
new_v=np.matmul(attention,v)

In [19]:
new_v

array([[-0.23143078,  0.41771085, -0.9566029 ,  2.51162707,  0.33619158,
        -0.25141886, -0.52519439,  1.82232727],
       [-0.34220325, -0.36205132, -1.72942942,  1.14306354, -0.31804358,
        -0.24615294, -0.46679716,  0.22622206],
       [-0.27747907, -0.32110083, -1.33564484,  0.72870235, -0.51003483,
        -0.04367272, -0.4864867 , -0.20065179],
       [ 0.04341404, -0.49607861, -0.95782287,  0.68965603, -0.07754716,
        -0.27130001, -0.63909043,  0.15704593]])

In [20]:
v

array([[-0.23143078,  0.41771085, -0.9566029 ,  2.51162707,  0.33619158,
        -0.25141886, -0.52519439,  1.82232727],
       [-0.37767614, -0.61175615, -1.97691323,  0.70480565, -0.52755065,
        -0.24446662, -0.44809649, -0.28490197],
       [ 0.10953515,  0.57877994,  1.11023215,  0.16875837, -0.75090929,
         0.84233845, -0.62701627, -0.60563191],
       [ 0.88396147, -1.34482923, -0.4916784 ,  0.40675127,  1.1027501 ,
        -1.11139771, -1.04623832,  0.95871604]])

In [23]:
def softmax(x):
  return (np.exp(x).T/np.sum(np.exp(x),axis=1)).T

def scaled_dot_product_attention(q,k,v,mask=None):
  d_k=q.shape[-1]
  scale=np.matmul(q,k.T)/math.sqrt(d_k)
  if mask is not None:
    scale=scale+mask
    attention=softmax(scale)
    out=np.matmul(attention,v)
    return out, attention


In [25]:
values,attention=scaled_dot_product_attention(q,k,v,mask=mask)

In [27]:
print('Q:', q)
print('K:', k)
print('V:', v)
print('new_v:', values)
print('attention:',attention )

Q: [[-9.77924898e-01  4.44572771e-01 -1.76604134e+00  1.01049752e+00
   6.64773710e-01  9.34487037e-01  6.02586918e-01 -1.33283925e+00]
 [-3.45223993e-01  1.30391441e-03 -2.95794871e-01  8.43922012e-01
  -4.60591697e-01  1.00572154e+00 -1.81640797e+00 -1.88911176e+00]
 [ 1.32401673e+00  5.71255374e-01 -1.36280135e+00  3.23912908e-01
   1.03632534e+00  4.23072523e-02 -4.59872772e-02  1.28447456e-02]
 [-4.74509385e-01  1.23100644e-01 -8.53185485e-01  1.50185937e+00
  -3.71231181e-01  2.96330877e-01  3.29859415e-02  4.24694493e-01]]
K: [[ 0.21622947  0.58724895  0.23548883 -1.46703762 -1.62682373 -1.40717059
  -1.39956953  0.16377519]
 [ 0.37623156 -0.7179211  -2.73028538  0.59713483  0.82860094  0.36641916
  -0.95163053 -0.26991242]
 [ 0.04004255 -1.05290654 -0.95500036 -0.96876043  0.49361471  0.80644317
   0.60348088  1.26782241]
 [ 0.63217599  1.40273558  0.65586497  0.53894631 -1.7029201   0.54899075
   1.94928337 -0.37493385]]
V: [[-0.23143078  0.41771085 -0.9566029   2.51162707  0.